//
// Article.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct Article: Codable {

    public var author: String?
    public var title: String?
    public var articleDescription: String?
    public var source: Source?
    public var url: String?
    public var urlToImage: String?
    public var content: String?

    public init(author: String?, title: String?, articleDescription: String?, source: Source?, url: String?, urlToImage: String?, content: String?) {
        self.author = author
        self.title = title
        self.articleDescription = articleDescription
        self.source = source
        self.url = url
        self.urlToImage = urlToImage
        self.content = content
    }

}
